spring:
  cloud:
    gateway:
      routes:
        - id: payment-service
          uri: http://localhost:8080
          predicates:
            - Path=/payment/**
          filters:
            - StripPrefix=1